# Generated by Django 5.1.5 on 2025-02-03 18:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='パチモン名')),
                ('toughness', models.IntegerField(verbose_name='タフネス')),
                ('power', models.IntegerField(verbose_name='パワー')),
                ('hardness', models.IntegerField(verbose_name='硬さ')),
                ('intelligence', models.IntegerField(verbose_name='賢さ')),
                ('power_sense', models.IntegerField(verbose_name='才能(パワー)')),
                ('hardness_sense', models.IntegerField(verbose_name='才能(硬さ)')),
                ('intelligence_sense', models.IntegerField(verbose_name='才能(賢さ)')),
                ('resistance', models.IntegerField(verbose_name='才能(耐性)')),
                ('speed', models.IntegerField(verbose_name='才能(速度)')),
                ('charactar', models.CharField(max_length=10, verbose_name='センス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
