# Generated by Django 5.1.5 on 2025-02-06 06:25

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='パチモン名')),
                ('toughness_stats', models.IntegerField(default=100, verbose_name='タフネス')),
                ('power_stats', models.IntegerField(default=100, verbose_name='パワー')),
                ('muscle_mass_stats', models.IntegerField(default=100, verbose_name='筋肉量')),
                ('intelligence_stats', models.IntegerField(default=100, verbose_name='賢さ')),
                ('resistance_stats', models.IntegerField(default=100, verbose_name='耐性')),
                ('speed_stats', models.IntegerField(default=100, verbose_name='速度')),
                ('toughness_sense', models.IntegerField(default=16, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='才能(タフネス)')),
                ('power_sense', models.IntegerField(default=16, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='才能(パワー)')),
                ('muscle_mass_sense', models.IntegerField(default=16, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='才能(筋肉量)')),
                ('intelligence_sense', models.IntegerField(default=16, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='才能(賢さ)')),
                ('resistance_sense', models.IntegerField(default=16, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='才能(耐性)')),
                ('speed_sense', models.IntegerField(default=16, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(31)], verbose_name='才能(速度)')),
                ('toughness_effort_value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(256)], verbose_name='努力指数(タフネス)')),
                ('power_effort_value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(256)], verbose_name='努力指数(パワー)')),
                ('muscle_mass_effort_value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(256)], verbose_name='努力指数(筋肉量)')),
                ('intelligence_effort_value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(256)], verbose_name='努力指数(賢さ)')),
                ('resistance_effort_value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(256)], verbose_name='努力指数(耐性)')),
                ('speed_effort_value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(256)], verbose_name='努力指数(速度)')),
                ('toughness', models.IntegerField(default=0, verbose_name='実数値(タフネス)')),
                ('power', models.IntegerField(default=0, verbose_name='実数値(パワー)')),
                ('muscle_mass', models.IntegerField(default=0, verbose_name='実数値(筋肉量)')),
                ('intelligence', models.IntegerField(default=0, verbose_name=' 実数値(賢さ)')),
                ('resistance', models.IntegerField(default=0, verbose_name='実数値(耐性)')),
                ('speed', models.IntegerField(default=0, verbose_name='実数値(速度)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
